### ISSUE TITLE
Enhancement request - Triggering the unlock command from TrueNAS server

### ISSUE THREAD

**Issue by DoraDeu** [ThorpeJosh/truenas-zfs-unlock#63] opened 2024-10-16 11:49 UTC
This is a great project and I think it implements an important mechanism to unlock encrypted datasets in a more secure way.
But wouldn´t it be even better if the "unlock" call would be (optional) triggered directly from the TrueNAS server?
I can imagine a post init script that is executed after the boot process of the TrueNAS server that calls a REST API on the docker container  as a trigger to execute the unlock script.
Whith that there is no need for executing it periodically via cron job.

**Comment by ThorpeJosh** [comment] 2024-11-09 13:29
Hi @DoraDeu, thanks for sharing your feedback on the project. I completely agree that an API request to run the unlock script would be better than cron. I noted some thoughts on this a while back in issue #13. I will have to test if Truenas requesting an unlock as post init script will work, as I know if the unlock doesn't happen at the correct timing, then all the shares, apps, and other Truenas services that rely on the unlocked dataset will fail to start.

I'll do some testing and report back.

**Comment by ThorpeJosh** [comment] 2024-11-09 13:37
> An option for multiple TrueNAS server would also be perfect. I have a productive TrueNAS Scale and and TrueNAS Scale as a backup system. Both have encrypted datasets. I guess it wouldn´t be too hard to enhance the code to support more than one server.

It would be pretty easy to add this functionality to the script. The issue may be the added complexity in the environment variables and to specify which pool/dataset belongs to which host (and potential conflicts if multiple hosts have the same pool/dataset names). So the env vars interface would need to be refactored.

The simpler solution would be to run a second container. Which personally I think this separation of keys in separate containers for separate Truenas servers is beneficial. Since the container only uses about 4mb of memory it shouldn't be a problem to run multiple instances.

Let me know your thoughts

**Comment by ThorpeJosh** [comment] 2024-11-17 10:52
I'll mark this as duplicate of  #13

Let me know if you want it reopened or feel free to raise another issue for other ideas.

**Closed by ThorpeJosh** 2024-11-17 10:52 UTC
Labels: duplicate
